name: Matrix with java version
on:
  push:
    branches:
      - main

jobs: 
  java-version:
    runs-on: ubuntu-latest
    steps:
      - name: log java version
        run: java -version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          tree
      - name: log java version
        run: java -version
