name: Matrix with java version
on:
  push:
    branches:
      - main

jobs: 
  java-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: log java version
        run: java -version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          tree
      - name: log java version
        run: java -version
