name: Matrix with java version
on:
  push:
    branches:
      - main

jobs: 
  java-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        java_versions: [11, 15, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: log java version
        run: java -version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java_versions }}
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: log java version
        run: java -version
