on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          ls .github
          cd .github
          ls -a
          tree
          cat /home/runner/work/github-action/github-action/.github/actions/hello/dist/index.js
      - name: execute my action
        uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - name: Echo time and list file by javascript code
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo "Files: ${{ steps.hello.outputs.files }}"
